name: Push Ruby Gem to rubygems.org.


on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input short release note or some useful messages.'
        required: true
        default: ''

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish to Rubygems
        uses: cadwallion/publish-rubygems-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
